stages:
  - build
  - deploy
  - notify

build-job:
  stage: build
  script:
    - docker build -t register-manager .

deploy-job:
  stage: deploy
  script:
    - docker-compose up -d
    - docker exec -it registry-web-1 python3 manage.py makemigrations
    - docker exec -it registry-web-1 python3 manage.py migrate
    - apk add curl
    - sh ci-notify.sh ✅

notify_error:
  stage: notify
  script:
  - apk add curl
  - sh ci-notify.sh ❌
  when: on_failure
