stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - docker build -t register-manager .

test-job:
  stage: test
  script:
    - docker run --rm register-manager pytest -s -v

deploy-job:
  stage: deploy
  script:
    - docker run -p 8553:8080 --rm -d register-manager pytest -s -v