stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - docker build -t register-manager .

deploy-job:
  stage: deploy
  script:
    - docker rm registry-manager
    - docker run -p 8553:8080 -d --name registry-manager --restart=always register-manager 