version: '3'
services:
    web:
        image: register-manager
        restart: always
        ports:
            - 8553:8080
        volumes:
            - /home/registry/media/:/app/media/
            - /home/registry/db/db.sqlite3:/app/db.sqlite3
