version: '3'
services:
    web:
        image: register-manager
        restart: always
        ports:
            - 8553:8080
        volumes:
            - ./media:/var/opt/registry-manager/media
            - ./db.sqlite3:/var/opt/registry-manager/db
