# Generated by Django 5.1.5 on 2025-02-05 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название ошибки')),
                ('description', models.TextField(verbose_name='Описание ошибки')),
                ('solving', models.TextField(verbose_name='Решение ошибки')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Красная', 'Красная'), ('Желтая', 'Желтая'), ('Зелёная', 'Зелёная'), ('Нет', 'Нет')], default='Нет', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.error', verbose_name='Фото')),
            ],
        ),
    ]
