# Generated by Django 5.1.5 on 2025-02-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_error_photo_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='photo',
            field=models.ImageField(upload_to='media/errors_screens'),
        ),
        migrations.AlterField(
            model_name='error',
            name='status',
            field=models.CharField(choices=[('Красная', 'Красная'), ('Желтая', 'Желтая'), ('Зелёная', 'Зелёная'), ('no', 'no')], default='no', max_length=10),
        ),
    ]
