# Generated by Django 5.1.5 on 2025-02-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_error_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='status',
            field=models.CharField(choices=[('Red', 'Красная'), ('Yellow', 'Желтая'), ('Green', 'Зелёная'), ('no', 'no')], default='no', max_length=10),
        ),
    ]
