# Generated by Django 5.1.5 on 2025-02-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_error_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/errors_screens/'),
        ),
    ]
