# Generated by Django 5.1.5 on 2025-02-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_error_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='photo',
            field=models.ImageField(null=True, upload_to='errors/%Y-%m-%d/'),
        ),
    ]
