# Generated by Django 4.2.17 on 2025-02-13 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='decision',
            field=models.CharField(choices=[('Red', 'Сложно'), ('Yellow', 'Среднее'), ('Green', 'Легко'), ('no', 'no')], default='no', max_length=30),
        ),
        migrations.AlterField(
            model_name='error',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Категория'),
        ),
    ]
