# Generated by Django 4.2.17 on 2025-02-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_error_decision_alter_error_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='error',
            options={'verbose_name': 'Записи ошибок', 'verbose_name_plural': 'Записи ошибок'},
        ),
        migrations.AlterField(
            model_name='error',
            name='decision',
            field=models.CharField(choices=[('Red', 'Сложно'), ('Yellow', 'Среднее'), ('Green', 'Легко'), ('no', 'no')], default='no', max_length=30, verbose_name='Сложность решения'),
        ),
        migrations.AlterField(
            model_name='error',
            name='photo',
            field=models.ImageField(null=True, upload_to='errors/%Y-%m-%d/', verbose_name='Фото ошибки'),
        ),
        migrations.AlterField(
            model_name='error',
            name='status',
            field=models.CharField(choices=[('Red', 'Красная'), ('Yellow', 'Желтая'), ('Green', 'Зелёная'), ('no', 'no')], default='no', max_length=10, verbose_name='Статус ошибки'),
        ),
    ]
