# Generated by Django 4.2.17 on 2025-02-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_telegramuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='created_at',
        ),
    ]
