# Generated by Django 4.2.17 on 2025-02-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_telegramuser_created_at'),
    ]

    operations = [
    ]
