# Generated by Django 4.2.17 on 2025-02-14 22:25

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_create_telegramuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание ошибки'),
        ),
        migrations.AlterField(
            model_name='error',
            name='solving',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Решение ошибки'),
        ),
    ]
