name: Docker RegistryImage CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v4
    - name: RegistryImages
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
